version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jwtsecret?&createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

server:
  error:
    include-stacktrace: on_param
  ###port: 8443
  ##ssl:
   ##key-store: keyStore.p12
    ##key-store-password: springboot
    ##keyStoreType: PKCS12

spring:
  application:
    name: SpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/jwtsecret?&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  springboot:
    image: companyapi/springboot:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    enviroment:
      <<: *database-variables
    mem_limit: 512m

jwt:
  secret: VEVOVEFERUNPRElGSUNBUkVTU0FQT0hBQVFVSQ==