server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: SpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/jwtsecret?&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

jwt:
  secret: WSWORKPORJECTKOTLIN